import csv
from pathlib import Path

project_root = Path(__file__).resolve().parent
csv_path = project_root.parent / 'data' / 'india_districts.csv'
output_path = project_root / 'forecast.py'

coords = []
with csv_path.open('r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        coords.append((row['district'], float(row['lat']), float(row['lon']), row['state']))

flood_plain = {
    'Kamrup', 'Barpeta', 'Dhubri', 'Morigaon', 'Patna', 'Darbhanga',
    'Sitamarhi', 'Muzaffarpur', 'Kendrapara', 'Alappuzha', 'Mumbai'
}

elevations = {}
for district, lat, lon, state in coords:
    elevations[district] = 10.0 if district in flood_plain else 100.0

state_capitals = {
    'Assam': {'lat': 26.15, 'lon': 91.79},
    'Bihar': {'lat': 25.61, 'lon': 85.13},
    'Uttar Pradesh': {'lat': 26.85, 'lon': 80.95},
    'West Bengal': {'lat': 22.57, 'lon': 88.36},
    'Odisha': {'lat': 20.27, 'lon': 85.83},
    'Kerala': {'lat': 10.85, 'lon': 76.27},
    'Maharashtra': {'lat': 19.08, 'lon': 72.88},
    'Tamil Nadu': {'lat': 13.08, 'lon': 80.27},
    'Karnataka': {'lat': 12.97, 'lon': 77.59},
    'Andhra Pradesh': {'lat': 17.38, 'lon': 78.47},
    'Telangana': {'lat': 17.39, 'lon': 78.49},
    'Gujarat': {'lat': 23.02, 'lon': 72.57},
    'Rajasthan': {'lat': 26.92, 'lon': 75.82},
    'Delhi': {'lat': 28.61, 'lon': 77.21},
    'Punjab': {'lat': 30.90, 'lon': 75.85},
    'Haryana': {'lat': 28.45, 'lon': 76.00},
    'Uttarakhand': {'lat': 30.32, 'lon': 78.03},
    'Jharkhand': {'lat': 23.35, 'lon': 85.33},
    'Chhattisgarh': {'lat': 21.25, 'lon': 81.63},
    'Madhya Pradesh': {'lat': 23.25, 'lon': 77.41},
}

with output_path.open('w', encoding='utf-8') as f:
    f.write('import os\n')
    f.write('from pathlib import Path\n')
    f.write('from datetime import datetime\n')
    f.write('\n')
    f.write('import numpy as np\n')
    f.write('import pandas as pd\n')
    f.write('import requests\n')
    f.write('import joblib\n')
    f.write('from plotly.subplots import make_subplots\n')
    f.write('import plotly.graph_objects as go\n')
    f.write('\n')
    f.write('PROJECT_ROOT = Path(__file__).resolve().parent.parent\n')
    f.write('MODELS_DIR = PROJECT_ROOT / \'models\'\n')
    f.write('DATA_DIR = PROJECT_ROOT / \'data\'\n')
    f.write('\n')
    f.write('FLOOD_PLAIN_DISTRICTS = {\n')
    f.write("    'Kamrup', 'Barpeta', 'Dhubri', 'Morigaon', 'Patna', 'Darbhanga',\n")
    f.write("    'Sitamarhi', 'Muzaffarpur', 'Kendrapara', 'Alappuzha', 'Mumbai'\n")
    f.write('}\n\n')
    f.write('STATE_CAPITAL_COORDS = {\n')
    for state, coords_state in state_capitals.items():
        f.write(f"    {state!r}: {{'lat': {coords_state['lat']:.2f}, 'lon': {coords_state['lon']:.2f}}},\n")
    f.write('}\n\n')
    f.write('ELEVATION_M = {\n')
    for district, elevation in elevations.items():
        f.write(f"    {district!r}: {elevation:.1f},\n")
    f.write('}\n\n')
    f.write('def get_district_coordinates():\n')
    f.write('    return {\n')
    for district, lat, lon, state in coords:
        f.write(f"        {district!r}: {{'lat': {lat:.2f}, 'lon': {lon:.2f}, 'state': {state!r}}},\n")
    f.write('    }\n\n')
    f.write('def get_7day_weather_forecast(district, state):\n')
    f.write('    coords = get_district_coordinates()\n')
    f.write('    if district not in coords:\n')
    f.write('        state_coord = STATE_CAPITAL_COORDS.get(state)\n')
    f.write('        if state_coord is None:\n')
    f.write('            state_coord = {\'lat\': 20.59, \'lon\': 78.96}\n')
    f.write('        lat = state_coord[\'lat\']\n')
    f.write('        lon = state_coord[\'lon\']\n')
    f.write('    else:\n')
    f.write('        lat = coords[district][\'lat\']\n')
    f.write('        lon = coords[district][\'lon\']\n')
    f.write('\n')
    f.write('    url = (\n')
    f.write('        f\"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}\"\n')
    f.write('        \"&daily=precipitation_sum,temperature_2m_max,temperature_2m_min,windspeed_10m_max\"\n')
    f.write('        \"&forecast_days=7\"\n')
    f.write('    )\n')
    f.write('\n')
    f.write('    try:\n')
    f.write('        response = requests.get(url, timeout=15)\n')
    f.write('        response.raise_for_status()\n')
    f.write('        data = response.json()\n')
    f.write('        return pd.DataFrame({\n')
    f.write('            \'date\': pd.to_datetime(data[\'daily\'][\'time\']),\n')
    f.write('            \'precipitation_mm\': data[\'daily\'][\'precipitation_sum\'],\n')
    f.write('            \'temp_max\': data[\'daily\'][\'temperature_2m_max\'],\n')
    f.write('            \'temp_min\': data[\'daily\'][\'temperature_2m_min\'],\n')
    f.write('            \'windspeed\': data[\'daily\'][\'windspeed_10m_max\'],\n')
    f.write('        })\n')
    f.write('    except Exception:\n')
    f.write('        today = datetime.now().date()\n')
    f.write('        estimates = []\n')
    f.write('        for day_index in range(7):\n')
    f.write('            date = today + pd.Timedelta(days=day_index)\n')
    f.write('            month = date.month\n')
    f.write('            base_rain = 5.0 if month in [11, 12, 1, 2, 3] else 25.0\n')
    f.write('            estimates.append({\n')
    f.write('                \'date\': pd.Timestamp(date),\n')
    f.write('                \'precipitation_mm\': float(base_rain),\n')
    f.write('                \'temp_max\': float(30.0 - (month % 12) * 0.5),\n')
    f.write('                \'temp_min\': float(20.0 - (month % 12) * 0.3),\n')
    f.write('                \'windspeed\': float(10.0 + (month % 12) * 0.4),\n')
    f.write('            })\n')
    f.write('        return pd.DataFrame(estimates)\n\n')
    f.write('def load_model_artifacts():\n')
    f.write('    model_path = MODELS_DIR / \'xgb_model.pkl\'\n')
    f.write('    scaler_path = MODELS_DIR / \'scaler.pkl\'\n')
    f.write('    features_path = MODELS_DIR / \'feature_names.pkl\'\n')
    f.write('    model = None\n')
    f.write('    scaler = None\n')
    f.write('    feature_names = []\n')
    f.write('    try:\n')
    f.write('        model = joblib.load(model_path)\n')
    f.write('    except Exception:\n')
    f.write('        model = None\n')
    f.write('    try:\n')
    f.write('        scaler = joblib.load(scaler_path)\n')
    f.write('    except Exception:\n')
    f.write('        scaler = None\n')
    f.write('    try:\n')
    f.write('        feature_names = joblib.load(features_path)\n')
    f.write('    except Exception:\n')
    f.write('        feature_names = []\n')
    f.write('    return model, scaler, feature_names\n\n')
    f.write('def build_daily_features(district, rainfall, river_level, temp, humidity, month):\n')
    f.write('    flood_plain_flag = 1 if district in FLOOD_PLAIN_DISTRICTS else 0\n')
    f.write('    elevation_m = ELEVATION_M.get(district, 100.0)\n')
    f.write('    rainfall_3day = rainfall * 3.0\n')
    f.write('    rainfall_7day = rainfall * 7.0\n')
    f.write('    api = rainfall * 0.75\n')
    f.write('    is_monsoon = 1 if month in [6, 7, 8, 9] else 0\n')
    f.write('    is_peak_monsoon = 1 if month in [7, 8] else 0\n')
    f.write('    month_sin = np.sin(2 * np.pi * month / 12)\n')
    f.write('    month_cos = np.cos(2 * np.pi * month / 12)\n')
    f.write('    river_level_pct = float(min(max(river_level / 10.0, 0.0), 1.0))\n')
    f.write('    rain_river_interaction = rainfall * river_level\n')
    f.write('    terrain_rain_risk = rainfall / (elevation_m + 1.0)\n')
    f.write('    flood_freq_5yr = 0.3 if flood_plain_flag else 0.1\n')
    f.write('    same_month_flood_rate = 0.35 if is_peak_monsoon else (0.25 if is_monsoon else 0.1)\n')
    f.write('    return {\n')
    f.write('        \'rainfall_mm\': float(rainfall),\n')
    f.write('        \'rainfall_3day\': float(rainfall_3day),\n')
    f.write('        \'rainfall_7day\': float(rainfall_7day),\n')
    f.write('        \'api\': float(api),\n')
    f.write('        \'elevation_m\': float(elevation_m),\n')
    f.write('        \'flood_plain_flag\': float(flood_plain_flag),\n')
    f.write('        \'is_monsoon\': float(is_monsoon),\n')
    f.write('        \'is_peak_monsoon\': float(is_peak_monsoon),\n')
    f.write('        \'month_sin\': float(month_sin),\n')
    f.write('        \'month_cos\': float(month_cos),\n')
    f.write('        \'river_level_pct\': float(river_level_pct),\n')
    f.write('        \'rain_river_interaction\': float(rain_river_interaction),\n')
    f.write('        \'terrain_rain_risk\': float(terrain_rain_risk),\n')
    f.write('        \'flood_freq_5yr\': float(flood_freq_5yr),\n')
    f.write('        \'same_month_flood_rate\': float(same_month_flood_rate),\n')
    f.write('    }\n\n')
    f.write('def align_features(feat_dict, feature_names):\n')
    f.write('    df = pd.DataFrame([feat_dict]).reindex(columns=feature_names, fill_value=0.0)\n')
    f.write('    return df\n\n')
    f.write('def predict_risk(model, scaler, feature_names, feat_dict):\n')
    f.write('    df = align_features(feat_dict, feature_names)\n')
    f.write('    if scaler is not None:\n')
    f.write('        try:\n')
    f.write('            df = scaler.transform(df)\n')
    f.write('        except Exception:\n')
    f.write('            df = df.values\n')
    f.write('    else:\n')
    f.write('        df = df.values\n')
    f.write('    if model is None:\n')
    f.write('        return 0.0\n')
    f.write('    try:\n')
    f.write('        prob = model.predict_proba(df)[0][1]\n')
    f.write('    except Exception:\n')
    f.write('        try:\n')
    f.write('            pred = model.predict(df)[0]\n')
    f.write('            prob = float(pred)\n')
    f.write('        except Exception:\n')
    f.write('            prob = 0.0\n')
    f.write('    return float(min(max(prob, 0.0), 1.0))\n\n')
    f.write('def classify_risk(prob_pct):\n')
    f.write('    if prob_pct < 30.0:\n')
    f.write('        return \'Low\', \'Green\'\n')
    f.write('    if prob_pct < 60.0:\n')
    f.write('        return \'Moderate\', \'Yellow\'\n')
    f.write('    if prob_pct < 80.0:\n')
    f.write('        return \'High\', \'Orange\'\n')
    f.write('    return \'Severe\', \'Red\'\n\n')
    f.write('def generate_7day_forecast(district, state):\n')
    f.write('    weather_df = get_7day_weather_forecast(district, state)\n')
    f.write('    model, scaler, feature_names = load_model_artifacts()\n')
    f.write('    forecast_rows = []\n')
    f.write('    for row in weather_df.itertuples(index=False):\n')
    f.write('        rainfall = float(row.precipitation_mm)\n')
    f.write('        date = row.date\n')
    f.write('        day = pd.Timestamp(date).strftime(\'%A\')\n')
    f.write('        temp_avg = float((row.temp_max + row.temp_min) / 2.0)\n')
    f.write('        river_level = float(get_river_level_estimate(rainfall, district))\n')
    f.write('        month = pd.Timestamp(date).month\n')
    f.write('        feat_dict = build_daily_features(district, rainfall, river_level, temp_avg, 70.0, month)\n')
    f.write('        try:\n')
    f.write('            prob = predict_risk(model, scaler, feature_names, feat_dict)\n')
    f.write('            if prob == 0.0:\n')
    f.write('                raise ValueError(\'Model returned zero or failed\')\n')
    f.write('        except Exception:\n')
    f.write('            flood_plain = 1 if district in FLOOD_PLAIN_DISTRICTS else 0\n')
    f.write('            is_monsoon = 1 if month in [6, 7, 8, 9] else 0\n')
    f.write('            prob = 0.1 + (rainfall / 200.0) + (flood_plain * 0.2) + (is_monsoon * 0.1)\n')
    f.write('            prob = float(min(max(prob, 0.0), 1.0))\n')
    f.write('        prob_pct = prob * 100.0\n')
    f.write('        risk_level, risk_color = classify_risk(prob_pct)\n')
    f.write('        forecast_rows.append({\n')
    f.write('            \'date\': pd.Timestamp(date),\n')
    f.write('            \'day\': day,\n')
    f.write('            \'precipitation_mm\': rainfall,\n')
    f.write('            \'flood_probability\': prob,\n')
    f.write('            \'flood_probability_pct\': prob_pct,\n')
    f.write('            \'risk_level\': risk_level,\n')
    f.write('            \'risk_color\': risk_color,\n')
    f.write('        })\n')
    f.write('    return pd.DataFrame(forecast_rows)\n\n')
    f.write('def plot_forecast_chart(forecast_df, district):\n')
    f.write('    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.12)\n')
    f.write('    risk_color_map = {\n')
    f.write('        \'Green\': \'green\',\n')
    f.write('        \'Yellow\': \'yellow\',\n')
    f.write('        \'Orange\': \'orange\',\n')
    f.write('        \'Red\': \'red\',\n')
    f.write('    }\n')
    f.write('    bar_colors = [risk_color_map.get(color, \'lightblue\') for color in forecast_df[\'risk_color\']]\n')
    f.write('    fig.add_trace(\n')
    f.write('        go.Bar(\n')
    f.write('            x=forecast_df[\'date\'],\n')
    f.write('            y=forecast_df[\'precipitation_mm\'],\n')
    f.write('            marker_color=bar_colors,\n')
    f.write('            name=\'Rainfall (mm)\',\n')
    f.write('        ),\n')
    f.write('        row=1, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_trace(\n')
    f.write('        go.Scatter(\n')
    f.write('            x=forecast_df[\'date\'],\n')
    f.write('            y=forecast_df[\'flood_probability_pct\'],\n')
    f.write('            mode=\'lines+markers\',\n')
    f.write('            line=dict(color=\'red\', width=3),\n')
    f.write('            marker=dict(size=8, color=\'red\'),\n')
    f.write('            name=\'Flood Probability (%)\',\n')
    f.write('        ),\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_shape(\n')
    f.write('        type=\'line\',\n')
    f.write('        xref=\'x\',\n')
    f.write('        yref=\'y2\',\n')
    f.write('        x0=forecast_df[\'date\'].iloc[0],\n')
    f.write('        x1=forecast_df[\'date\'].iloc[-1],\n')
    f.write('        y0=60,\n')
    f.write('        y1=60,\n')
    f.write('        line=dict(color=\'red\', width=2, dash=\'dash\'),\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_shape(\n')
    f.write('        type=\'rect\',\n')
    f.write('        xref=\'x\',\n')
    f.write('        yref=\'y2\',\n')
    f.write('        x0=forecast_df[\'date\'].iloc[0],\n')
    f.write('        x1=forecast_df[\'date\'].iloc[-1],\n')
    f.write('        y0=0,\n')
    f.write('        y1=30,\n')
    f.write('        fillcolor=\'green\',\n')
    f.write('        opacity=0.1,\n')
    f.write('        line_width=0,\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_shape(\n')
    f.write('        type=\'rect\',\n')
    f.write('        xref=\'x\',\n')
    f.write('        yref=\'y2\',\n')
    f.write('        x0=forecast_df[\'date\'].iloc[0],\n')
    f.write('        x1=forecast_df[\'date\'].iloc[-1],\n')
    f.write('        y0=30,\n')
    f.write('        y1=60,\n')
    f.write('        fillcolor=\'yellow\',\n')
    f.write('        opacity=0.1,\n')
    f.write('        line_width=0,\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_shape(\n')
    f.write('        type=\'rect\',\n')
    f.write('        xref=\'x\',\n')
    f.write('        yref=\'y2\',\n')
    f.write('        x0=forecast_df[\'date\'].iloc[0],\n')
    f.write('        x1=forecast_df[\'date\'].iloc[-1],\n')
    f.write('        y0=60,\n')
    f.write('        y1=80,\n')
    f.write('        fillcolor=\'orange\',\n')
    f.write('        opacity=0.1,\n')
    f.write('        line_width=0,\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.add_shape(\n')
    f.write('        type=\'rect\',\n')
    f.write('        xref=\'x\',\n')
    f.write('        yref=\'y2\',\n')
    f.write('        x0=forecast_df[\'date\'].iloc[0],\n')
    f.write('        x1=forecast_df[\'date\'].iloc[-1],\n')
    f.write('        y0=80,\n')
    f.write('        y1=100,\n')
    f.write('        fillcolor=\'red\',\n')
    f.write('        opacity=0.1,\n')
    f.write('        line_width=0,\n')
    f.write('        row=2, col=1,\n')
    f.write('    )\n')
    f.write('    fig.update_layout(\n')
    f.write('        title=f\'7-Day Flood Risk Forecast — {district}\',\n')
    f.write('        xaxis_title=\'Date\',\n')
    f.write('        yaxis_title=\'Rainfall (mm)\',\n')
    f.write('        yaxis2_title=\'Flood Probability (%)\',\n')
    f.write('        legend=dict(orientation=\'h\', yanchor=\'bottom\', y=1.02, xanchor=\'right\', x=1),\n')
    f.write('    )\n')
    f.write('    fig.update_yaxes(title_text=\'Rainfall (mm)\', row=1, col=1)\n')
    f.write('    fig.update_yaxes(title_text=\'Flood Probability (%)\', row=2, col=1)\n')
    f.write('    return fig\n\n')
    f.write('def get_forecast_summary(forecast_df, district):\n')
    f.write('    if forecast_df.empty:\n')
    f.write('        return f\"No forecast data available for {district}.\"\n')
    f.write('    peak_idx = int(forecast_df[\'flood_probability_pct\'].idxmax())\n')
    f.write('    peak_row = forecast_df.loc[peak_idx]\n')
    f.write('    peak_day = peak_row[\'day\']\n')
    f.write('    peak_prob = peak_row[\'flood_probability_pct\']\n')
    f.write('    total_rain = float(forecast_df[\'precipitation_mm\'].sum())\n')
    f.write('    high_days = int((forecast_df[\'flood_probability_pct\'] > 60.0).sum())\n')
    f.write('    severe_days = int((forecast_df[\'flood_probability_pct\'] > 80.0).sum())\n')
    f.write('    risk_label = peak_row[\'risk_level\']\n')
    f.write('    if peak_prob > 80.0:\n')
    f.write('        recommendation = \'Severe flooding is likely. Evacuate low-lying areas and follow official orders.\'\n')
    f.write('    elif peak_prob > 60.0:\n')
    f.write('        recommendation = \'High flood risk is expected. Prepare emergency supplies and stay alert.\'\n')
    f.write('    elif peak_prob > 30.0:\n')
    f.write('        recommendation = \'Moderate flood risk is expected. Monitor local weather and avoid risky travel.\'\n')
    f.write('    else:\n')
    f.write('        recommendation = \'Low flood risk is expected. Continue routine precautions.\'\n')
    f.write('    return (\n')
    f.write('        f\"7-Day Forecast Summary for {district}:\n\"\n')
    f.write('        f\"- Highest risk day: {peak_day} with {peak_prob:.1f}% probability ({risk_label})\n\"\n')
    f.write('        f\"- Total rainfall expected: {total_rain:.1f} mm\n\"\n')
    f.write('        f\"- High risk days (>60%): {high_days}\n\"\n')
    f.write('        f\"- Severe risk days (>80%): {severe_days}\n\"\n')
    f.write('        f\"- Recommendation: {recommendation}\n\"\n')
    f.write('        f\"- Emergency numbers: 1070, 112\"\n')
    f.write('    )\n\n')
    f.write('if __name__ == \'__main__\':\n')
    f.write('    forecast = generate_7day_forecast(\'Kamrup\', \'Assam\')\n')
    f.write('    print(get_forecast_summary(forecast, \'Kamrup\'))\n')
    f.write('    print(forecast[[\'date\', \'day\', \'precipitation_mm\', \'flood_probability_pct\', \'risk_level\']])\n')
