"""Flood risk report generation using fpdf2 for FloodGuard AI."""

from __future__ import annotations

import datetime
from typing import Any
from fpdf import FPDF

from src.crop_loss_estimator import (
    get_crop_data,
    get_crop_prices,
    get_yield_per_hectare,
    get_crop_vulnerability,
    estimate_crop_loss,
    get_compensation_schemes,
)

class FloodReportPDF(FPDF):
    """Custom FPDF2 subclass for FloodGuard AI report headers and footers."""
    
    def __init__(self, district: str, state: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.district = district
        self.state = state
        self.report_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.report_id = f"FG-{int(datetime.datetime.now().timestamp())}"
        self.alias_nb_pages()
        
    def footer(self) -> None:
        """Render the running page footer with disclaimer and page numbers."""
        self.set_y(-16)
        self.set_font("helvetica", "I", 7.5)
        self.set_text_color(100, 116, 139) # slate-500
        
        # Center-aligned running disclaimer
        self.cell(0, 4, "Generated by FloodGuard AI | Data sources: IMD, NDMA, OpenWeatherMap", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, "Disclaimer: This report is AI-generated for advisory purposes only. Farmers should verify with local authorities.", align="C", new_x="LMARGIN", new_y="NEXT")
        
        # Right-aligned page numbers
        self.set_y(-12)
        self.set_font("helvetica", "", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="R")


def generate_flood_report(
    district: str,
    state: str,
    risk_score: float,
    risk_level: str,
    weather_data: dict[str, Any] | None = None,
    crop_data: dict[str, Any] | None = None,
    model_scores: dict[str, float] | None = None,
) -> bytes:
    """Generate a premium, professional flood risk assessment PDF report.

    Args:
        district: Name of the district.
        state: Name of the state.
        risk_score: Calculated risk score (0-100 or 0-1).
        risk_level: Mapped risk level category (e.g., LOW, MEDIUM, HIGH, CRITICAL).
        weather_data: Optional dictionary containing current weather and 7-day forecast.
        crop_data: Optional dictionary containing agricultural impact estimates.
        model_scores: Optional dictionary of individual model confidence levels.

    Returns:
        bytes: The generated PDF document.
    """
    # 1. Normalize risk score to 0-100 range
    if risk_score <= 1.0:
        risk_score = risk_score * 100.0

    # 2. Determine normalized risk level & color scheme
    # LOW = green (#4CAF50)
    # MEDIUM = orange (#FF9800)
    # HIGH = red (#F44336)
    # CRITICAL = dark red (#B71C1C)
    lvl_upper = risk_level.upper()
    if lvl_upper in ("SAFE", "LOW"):
        risk_lvl_norm = "LOW"
        r_col, g_col, b_col = 76, 175, 80 # #4CAF50
    elif lvl_upper in ("WATCH", "MODERATE", "MEDIUM"):
        risk_lvl_norm = "MEDIUM"
        r_col, g_col, b_col = 255, 152, 0 # #FF9800
    elif lvl_upper in ("DANGER", "HIGH"):
        risk_lvl_norm = "HIGH"
        r_col, g_col, b_col = 244, 67, 54 # #F44336
    else:
        risk_lvl_norm = "CRITICAL"
        r_col, g_col, b_col = 183, 28, 28 # #B71C1C

    # 3. Model score fallbacks
    if not model_scores:
        model_scores = {
            "xgboost": risk_score,
            "lstm": max(0.0, min(100.0, risk_score * 0.95 + (2.0 if risk_score < 50 else -3.0))),
            "ensemble": risk_score
        }

    # 4. Weather data defaults if None
    if not weather_data:
        weather_data = {
            "current": None,
            "forecast": None
        }

    # 5. Crop data fallbacks
    if not crop_data:
        state_crops = get_crop_data().get(state, ["Rice", "Jute", "Vegetables"])[:3]
        area_per_crop = {crop: 5.0 for crop in state_crops} # default 5 hectares per crop
        try:
            crop_data = estimate_crop_loss(
                state=state,
                selected_crops=state_crops,
                area_per_crop=area_per_crop,
                flood_probability=risk_score / 100.0,
                flood_duration_days=5,
                season="Kharif",
            )
        except Exception:
            crop_data = None

    # Initialize FPDF
    pdf = FloodReportPDF(district, state)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    # ==========================================
    # PAGE 1: META, RISK & WEATHER
    # ==========================================

    # --- HEADER BLOCK (PAGE 1 ONLY) ---
    pdf.set_fill_color(15, 23, 42) # Slate-900 (#0F172A)
    pdf.rect(15, 15, 180, 24, style="F")

    # Logo Text & App Name
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(20, 18)
    pdf.set_font("helvetica", "B", 17)
    pdf.cell(170, 8, "FloodGuard AI", border=0)
    
    # Subtitle
    pdf.set_xy(20, 26)
    pdf.set_font("helvetica", "B", 7.5)
    pdf.set_text_color(0, 188, 212) # Cyan color (#00BCD4)
    pdf.cell(170, 4, "INDIA FLOOD RISK PREDICTION & AGRICULTURAL INTELLIGENCE SYSTEM", border=0)

    # Accent Cyan Band
    pdf.set_fill_color(0, 188, 212)
    pdf.rect(15, 39, 180, 2.2, style="F")

    # --- SECTION 1: LOCATION DETAILS ---
    pdf.set_xy(15, 48)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59) # slate-800
    pdf.cell(180, 5, "1. Location Details & Metadata", new_x="LMARGIN", new_y="NEXT")
    
    # Colored underline
    pdf.set_draw_color(0, 188, 212)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)

    # Metadata Grid
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139) # slate-500
    
    # Row 1
    pdf.cell(32, 6, "District Name:")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(58, 6, district)
    
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(32, 6, "State / UT:")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(58, 6, state, new_x="LMARGIN", new_y="NEXT")

    # Row 2
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(32, 6, "Coordinates:")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    
    # Fallback coordinates mapping if not available
    lat_val, lon_val = 20.5937, 78.9629 # Default center of India
    coords_text = "N/A"
    if weather_data and weather_data.get("current") and weather_data["current"].get("lat") is not None:
        lat_val = weather_data["current"].get("lat")
        lon_val = weather_data["current"].get("lon")
        coords_text = f"{lat_val:.4f} N, {lon_val:.4f} E"
    pdf.cell(58, 6, coords_text)

    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(32, 6, "Report ID:")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(58, 6, pdf.report_id, new_x="LMARGIN", new_y="NEXT")

    # Row 3
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(32, 6, "Generated On:")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(148, 6, pdf.report_date, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(3)

    # --- SECTION 2: AI RISK ASSESSMENT ---
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(180, 5, "2. AI Flood Risk Assessment", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_draw_color(0, 188, 212)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3.5)

    card_y = pdf.get_y()

    # A: Prominent Left Card (Risk Gauge Info)
    pdf.set_fill_color(248, 250, 252) # slate-50
    pdf.set_draw_color(r_col, g_col, b_col)
    pdf.set_line_width(0.8)
    pdf.rect(15, card_y, 58, 38, style="FD")

    pdf.set_xy(15, card_y + 4)
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(r_col, g_col, b_col)
    pdf.cell(58, 10, f"{risk_score:.0f}%", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(card_y + 16)
    pdf.set_font("helvetica", "B", 11.5)
    pdf.cell(58, 6, f"{risk_lvl_norm} RISK", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(card_y + 24)
    pdf.set_font("helvetica", "I", 7.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(58, 5, "Ensemble Confidence Level", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(58, 4, "Predictive Risk Index", align="C")

    # B: Sub-Table comparing model predictions (Right Card)
    pdf.set_xy(78, card_y)
    pdf.set_draw_color(226, 232, 240) # slate-200
    pdf.set_line_width(0.2)
    pdf.rect(78, card_y, 117, 38, style="D")

    # Sub-table Header
    pdf.set_xy(81, card_y + 2)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(48, 5, "AI Prediction Model Pipeline")
    pdf.cell(32, 5, "Probability Score")
    pdf.cell(31, 5, "Pipeline Status", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_draw_color(241, 245, 249)
    pdf.line(80, card_y + 8, 192, card_y + 8)

    # Row 1: XGBoost
    pdf.set_xy(81, card_y + 9.5)
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(48, 5, "XGBoost Tabular Predictor")
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(32, 5, f"{model_scores['xgboost']:.1f}%")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(22, 163, 74) # green-600
    pdf.cell(31, 5, "Active / Table", new_x="LMARGIN", new_y="NEXT")

    # Row 2: LSTM
    pdf.set_xy(81, card_y + 16.5)
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(48, 5, "LSTM Sequence Neural Net")
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(32, 5, f"{model_scores['lstm']:.1f}%")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(31, 5, "Active / Sequence", new_x="LMARGIN", new_y="NEXT")

    # Row 3: Ensemble
    pdf.set_xy(81, card_y + 23.5)
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(48, 5, "Combined Ensemble Core")
    pdf.set_text_color(r_col, g_col, b_col)
    pdf.cell(32, 5, f"{model_scores['ensemble']:.1f}%")
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(0, 188, 212)
    pdf.cell(31, 5, "Weighted Output", new_x="LMARGIN", new_y="NEXT")

    # Row 4: Info Note
    pdf.set_xy(81, card_y + 30.5)
    pdf.set_font("helvetica", "I", 7.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(111, 4, "Ensemble combines meteorological and regional topological parameters.")

    pdf.set_xy(15, card_y + 38)
    pdf.ln(5)

    # --- SECTION 3: WEATHER DATA ---
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(180, 5, "3. Live Weather & Meteorological Feeds", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_draw_color(0, 188, 212)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)

    curr = weather_data.get("current")
    if curr:
        temp_val = curr.get("temp", curr.get("temperature_c"))
        temp = f"{temp_val:.1f} °C" if temp_val is not None else "N/A"
        hum = f"{curr.get('humidity', curr.get('humidity_pct'))}%" if curr.get("humidity", curr.get("humidity_pct")) is not None else "N/A"
        rain_mm = curr.get("rainfall", curr.get("rainfall_mm"))
        rain = f"{rain_mm:.1f} mm" if rain_mm is not None else "N/A"
        desc = curr.get("description", curr.get("weather_description", "Offline")).title()
    else:
        temp, hum, rain, desc = "N/A", "N/A", "N/A", "Offline (Weather Station Feeds)"

    # Current weather details box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_line_width(0.2)
    pdf.rect(15, pdf.get_y(), 180, 13, style="FD")

    pdf.set_y(pdf.get_y() + 2)
    pdf.set_x(18)
    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(32, 5.5, "Meteorological Feed:")
    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(48, 5.5, desc)

    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(14, 5.5, "Temp:")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(20, 5.5, temp)

    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(18, 5.5, "Humidity:")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(16, 5.5, hum)

    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(16, 5.5, "Rainfall:")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(16, 5.5, rain, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # 7-Day Forecast Grid
    pdf.set_font("helvetica", "B", 9.5)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(180, 5, "7-Day Precipitation & Local Inundation Forecast", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2.5)

    forecast_list = weather_data.get("forecast")
    if forecast_list and len(forecast_list) > 0:
        # Table Header
        pdf.set_fill_color(226, 232, 240) # slate-200
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(42, 6, " Date & Day", border=1, fill=True)
        pdf.cell(42, 6, " Precipitation Amount", border=1, fill=True)
        pdf.cell(42, 6, " Calculated Flood Risk", border=1, fill=True)
        pdf.cell(54, 6, " Forecast Advisory Status", border=1, fill=True, ln=1)

        pdf.set_font("helvetica", "", 8.5)
        pdf.set_text_color(15, 23, 42)
        
        # Display first 7 rows
        for row in forecast_list[:7]:
            d_val = row.get("date", "N/A")
            day_name = row.get("day", "N/A")[:3]
            precip_val = row.get("precipitation_mm", 0.0)
            prob_val = float(row.get("flood_probability_pct", row.get("flood_probability", 0.0) * 100))
            lvl_val = row.get("risk_level", "Low").upper()
            
            pdf.cell(42, 5.5, f" {d_val} ({day_name})", border=1)
            pdf.cell(42, 5.5, f" {precip_val:.1f} mm", border=1)
            pdf.cell(42, 5.5, f" {prob_val:.1f}%", border=1)
            
            # Text coloring based on forecast risk
            if lvl_val in ("SAFE", "LOW"):
                pdf.set_text_color(22, 163, 74)
            elif lvl_val in ("WATCH", "MODERATE", "MEDIUM"):
                pdf.set_text_color(217, 119, 6) # amber-600
            else:
                pdf.set_text_color(220, 38, 38) # red-600
                
            pdf.cell(54, 5.5, f" {lvl_val}", border=1, ln=1)
            pdf.set_text_color(15, 23, 42) # reset
    else:
        # Display neat offline details
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(15, pdf.get_y(), 180, 16, style="FD")
        pdf.set_xy(18, pdf.get_y() + 5)
        pdf.set_font("helvetica", "I", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(174, 6, "Live 7-day meteorological forecast stream is currently offline.", align="C", ln=1)


    # ==========================================
    # PAGE 2: AGRICULTURE & RECOMMENDATIONS
    # ==========================================
    pdf.add_page()

    # --- SECTION 4: AGRICULTURAL IMPACT ---
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(180, 5, "4. Agricultural Vulnerability & Loss Assessment", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_draw_color(0, 188, 212)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3.5)

    if crop_data:
        avg_damage = crop_data.get("avg_damage_pct", 0.0)
        tot_loss_inr = crop_data.get("total_loss_inr", 0)
        tot_area = crop_data.get("total_area_ha", 0.0)
        worst_c = crop_data.get("worst_crop", "N/A")
        
        # Financial formatting in INR (Lakhs/Crores helper)
        if tot_loss_inr < 100000:
            loss_formatted = f"INR {tot_loss_inr:,.0f}"
        elif tot_loss_inr < 10000000:
            loss_formatted = f"INR {tot_loss_inr / 100000:.2f} Lakhs"
        else:
            loss_formatted = f"INR {tot_loss_inr / 10000000:.2f} Crores"
            
        # Summary Box
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(15, pdf.get_y(), 180, 16, style="FD")
        
        pdf.set_y(pdf.get_y() + 2)
        pdf.set_x(18)
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(24, 6, "Total Area:")
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(32, 6, f"{tot_area:.2f} ha")
        
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(28, 6, "Average Damage:")
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(r_col, g_col, b_col)
        pdf.cell(32, 6, f"{avg_damage:.1f}%")
        
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(32, 6, "Financial Loss Est:")
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(r_col, g_col, b_col)
        pdf.cell(32, 6, loss_formatted, new_x="LMARGIN", new_y="NEXT")

        pdf.ln(5)

        # Crop Loss Details Table
        pdf.set_font("helvetica", "B", 9.5)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(180, 5, "Crop-wise Expected Loss Breakdown", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2.5)

        pdf.set_fill_color(226, 232, 240)
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(42, 6, " Crop Type", border=1, fill=True)
        pdf.cell(36, 6, " Cultivated Area (ha)", border=1, fill=True)
        pdf.cell(48, 6, " Expected Inundation Damage", border=1, fill=True)
        pdf.cell(54, 6, " Financial Damage Valuation", border=1, fill=True, ln=1)

        pdf.set_font("helvetica", "", 8.5)
        pdf.set_text_color(15, 23, 42)
        
        for crop_row in crop_data.get("crops", []):
            crop_name = crop_row.get("crop")
            c_area = crop_row.get("area_ha", 0.0)
            c_dmg = crop_row.get("damage_pct", 0.0)
            c_loss = crop_row.get("loss_inr", 0.0)
            
            pdf.cell(42, 5.5, f" {crop_name}", border=1)
            pdf.cell(36, 5.5, f" {c_area:.2f} ha", border=1)
            pdf.cell(48, 5.5, f" {c_dmg:.1f}%", border=1)
            pdf.cell(54, 5.5, f" INR {c_loss:,.0f}", border=1, ln=1)

        # High Vulnerability Warning Box
        pdf.ln(4)
        pdf.set_fill_color(254, 242, 242) # red-50
        pdf.set_draw_color(252, 165, 165) # red-200
        pdf.rect(15, pdf.get_y(), 180, 16, style="FD")
        
        pdf.set_y(pdf.get_y() + 2.5)
        pdf.set_x(18)
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(153, 27, 27) # red-800
        pdf.cell(174, 5, " AGRICULTURAL ADVISORY WARNING:", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_x(18)
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(153, 27, 27)
        # Suggest low vulnerability alternatives
        pdf.cell(174, 5, f"Based on {risk_lvl_norm} risk, avoid sowing Potato, Onion, or Vegetables. Prefer Jute or early Rice harvest.")
        pdf.set_y(pdf.get_y() + 5)
    else:
        # Fallback empty agricultural section
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(15, pdf.get_y(), 180, 15, style="FD")
        pdf.set_xy(18, pdf.get_y() + 5)
        pdf.set_font("helvetica", "I", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(174, 6, "No agricultural loss assessment requested for this report.", align="C", ln=1)

    pdf.set_y(pdf.get_y() + 8)
    pdf.ln(5)

    # --- SECTION 5: RECOMMENDED ACTIONS ---
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(180, 5, "5. Recommended Emergency Actions & Government Schemes", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_draw_color(0, 188, 212)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3.5)

    # Action Items Layout
    # High risk = severe recommendations, low risk = monitoring recommendations
    if risk_lvl_norm in ("HIGH", "CRITICAL"):
        imm_actions = [
            "MOVE FAMILY, ELDERS, AND LIVESTOCK TO DESIGNATED HIGHER GROUND IMMEDIATELY.",
            "Pack all land records, identity credentials, and cash in airtight waterproof casings.",
            "De-energize all electric main supplies and lock gas cylinders before departure.",
            "Strictly avoid crossing active drainage canals, waterlogged fields, or submerged bridges."
        ]
        st_actions = [
            "Initiate emergency premature harvest of standing mature crops.",
            "Delay chemical fertilizer sprays or seed sowings to prevent washouts.",
            "Secure loose grain containers in elevated, sealed silos.",
            "Contact your block agricultural office or local disaster committee for rescue vectors."
        ]
    elif risk_lvl_norm == "MEDIUM":
        imm_actions = [
            "Monitor regional IMD rainfall and water-level charts on the FloodGuard AI dashboard.",
            "Establish community warning markers near local streams.",
            "Confirm availability of elevated cattle shelters.",
            "Keep emergency contact lines charged and dry."
        ]
        st_actions = [
            "Clean blockages from farm canals to maximize drainage rates.",
            "Prepare clean plastic sheeting to shield sensitive crops.",
            "Apply prophylactic pest controls to combat high-humidity damp-offs.",
            "Pre-register under PM Fasal Bima Yojana (PMFBY) before active monsoon surges."
        ]
    else:
        imm_actions = [
            "Maintain baseline situational awareness; no active flood warning is active.",
            "Participate in local block drainage clean-up drives.",
            "Ensure seeds are stored on palettes rather than raw dirt floors."
        ]
        st_actions = [
            "Follow standard agronomic calendars for sowing and field preparation.",
            "Ensure proper crop rotation schedules to optimize soil structure.",
            "Maintain general field drainage channels clear."
        ]

    # Render Bullets: Immediate Actions
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(194, 65, 12) # orange-700
    pdf.cell(180, 5, "Immediate Safety Measures (Next 24 Hours):", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    
    for bullet in imm_actions:
        pdf.cell(5, 5.5, chr(149), ln=0)
        pdf.multi_cell(175, 5.5, bullet, new_x="LMARGIN", new_y="NEXT")
        
    pdf.ln(3)

    # Render Bullets: Short-Term Actions
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(22, 101, 52) # green-800
    pdf.cell(180, 5, "Short-Term Agricultural Tactics (Next 7 Days):", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(15, 23, 42)
    
    for bullet in st_actions:
        pdf.cell(5, 5.5, chr(149), ln=0)
        pdf.multi_cell(175, 5.5, bullet, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Available Government Compensation Schemes Sub-Section
    pdf.set_font("helvetica", "B", 9.5)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(180, 5, "Applicable Central & State Relief Compensation Channels", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2.5)

    # Grid for schemes: PMFBY, SDRF, NDRF
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(15, pdf.get_y(), 180, 25, style="FD")

    pdf.set_y(pdf.get_y() + 2)
    
    # Scheme 1: PMFBY
    pdf.set_x(18)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(56, 4.5, "1. PM Fasal Bima Yojana (PMFBY)")
    
    # Scheme 2: SDRF
    pdf.set_font("helvetica", "B", 8)
    pdf.cell(56, 4.5, "2. State Disaster Relief Fund (SDRF)")
    
    # Scheme 3: NDRF
    pdf.set_font("helvetica", "B", 8)
    pdf.cell(50, 4.5, "3. National Disaster Fund (NDRF)", new_x="LMARGIN", new_y="NEXT")

    # Details Row 1
    pdf.set_x(18)
    pdf.set_font("helvetica", "", 7.5)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(56, 4.5, "Crop insurance support against washouts.")
    pdf.cell(56, 4.5, "Automatic compensation up to Rs 6,800/ha.")
    pdf.cell(50, 4.5, "Relief trigger for declared major disasters.", new_x="LMARGIN", new_y="NEXT")

    # Details Row 2
    pdf.set_x(18)
    pdf.set_font("helvetica", "I", 7.5)
    pdf.set_text_color(0, 188, 212)
    pdf.cell(56, 4.5, "Helpline: 1800-180-1111 (pmfby.gov.in)")
    pdf.cell(56, 4.5, "Apply at District Collector / Revenue Office")
    pdf.cell(50, 4.5, "Helpline: 1078 (ndma.gov.in)", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
