[theme]
base = "dark"
primaryColor = "#0ea5a4"
backgroundColor = "#101827"
secondaryBackgroundColor = "#182235"
textColor = "#e6edf7"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 20
