[theme]
base = "dark"
primaryColor = "#f97316"
backgroundColor = "#18181b"
secondaryBackgroundColor = "#27272a"
textColor = "#fafafa"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 20

[client]
toolbarMode = "minimal"
